# Generated by Django 3.1 on 2021-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
