# Generated by Django 3.1 on 2021-03-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_draft'),
        ('ratings', '0002_rating_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.post', verbose_name='пост'),
        ),
    ]
