# Generated by Django 3.1 on 2021-03-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_moi_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='moi_text',
            new_name='telegram_bot',
        ),
    ]
